### ISSUE TITLE
[BUG] Translation

### ISSUE THREAD

**Issue by wasyady** [KewaiiGamer/Store-CoinFlip#2]
I tried your plugin, but I was a problem:

[SM] Warning(s) encountered in translation file "kewaii_coinflip.phrases.txt"
[SM] Invalid token ' ' in #format property on line 5.
[SM] Invalid token ' ' in #format property on line 5.
[SM] Invalid token ' ' in #format property on line 11.
[SM] Invalid token ' ' in #format property on line 11.

**Comment by KewaiiGamer** [comment]
As the log says, it's a warning. It doesn't break the plugin so it should still work. It should be fixed soon enough

Thanks for reporting :)

**Comment by wasyady** [comment]
Thank you in advance! 👍 

I sent pull request too! :flushed:
